= Bookmarks

These are my personal bookmarks to things I'm reading, have read, and  resources I find useful or interesting. Some of them might be NSFW.
I don't vet every writer I link here, so if someone does something shitty  please let me know and I'll reconsider if I want them on the list.

---

- Books, Pamphlets & Zines

@https://libcom.org/files/%5BMark_Fisher%5D_Capitalist_Realism_Is_There_no_Alte(BookZZ.org).pdf Capitalist Realism, Mark Fisher
@https://libcom.org/files/__Debt__The_First_5_000_Years.pdf Debt: The First 5,000 Years, David Graeber
@https://plain-text.co/"  The Plain Person's Guide to Plain Text Social Science , Kieran Healy
@https://indefenseofdegrowth.com/" In defense of degrowth, Giorgos Kallis
@https://theanarchistlibrary.org/library/lao-tzu-tao-te-ching Tao Te Ching, translated by Ursula K. Le Guin
@https://albanycomplementaryhealth.com/wp-content/uploads/2016/07/TaoTeChing-LaoTzu-StephenMitchellTranslation-33p.pdf Tao Te Ching, translated by Stephen Mitchell
@https://theanarchistlibrary.org/library/zabalaza-an-anarchist-organising-manual An Anarchist Organising Manual, Zabalaza
@https://solar.lowtechmagazine.com/posts/index.xml" Low Tech Magazine 


---

-Articles & Letters


@https://i.redd.it/ddesodoz9ccy.jpg" Pat the Bunny's retirement letter
@https://www.reddit.com/r/FolkPunk/comments/5qkhzm/comment/dczyogp/?utm_source=share&utm_medium=web2x&context=3" Pat the Bunny's retirement letter > and a typed version
@https://thagomizer.com/blog/2017/09/29/we-don-t-do-that-here.html We Don't Do That Here, Aja Hammerly
@https://emergencemagazine.org/essay/on-the-language-of-the-deep-blue/ On the Language of the Deep Blue, Charles Foster
@https://sadgrl.online/cyberspace/internet-manifesto.html Internet Manifesto, sadgrl.online
@https://idiomdrottning.org/who-can-fix-it"  Who can fix it?, idiomdrottning
@https://coolguy.website/basic-html-competency-is-the-new-punk-folk-explosion/ Basic HTML Competency Is the New Punk Folk Explosion!, Zach Mandeville
@https://tmo.smol.pub/1658707407"  zine-making, and the benefits it provides (in my eyes), TMO
@https://slimemoldtimemold.com/2022/08/04/effective-illegalism/ Effective Illegalism, Slime Mold Time Mold
@https://theanarchistlibrary.org/library/andie-nordgren-the-short-instructional-manifesto-for-relationship-anarchy The short instructional manifesto for relationship anarchy, Andie Nordgren

---

-Websites

Some cool, interesting or beautiful websites. I'm a fan of bookmark lists, so where I can find them I've linked to that! These are very roughly in order of "when I discovered them". By which I mean I just stick new ones on the end.


@https://memex.marginalia.nu/links/bookmarks.gmi       memex.marginalia.nu
@https://100r.co                                       100r 
@https://wiki.xxiivv.com/site/bookmarks.html           XXIIVV
@https://avanier.studio                                avanier 
@https://ritualdust.com/about/bookmarks/               Ritual Dust
@https://selfcare.tech/                                selfcare.tech 
@https://tiuraniemi.org/blog                           tiuraniemi 
@https://noelle.dev/                                   Noelle.dev 
@https://drewdevault.com/                              Drew DeVault 
@https://degrowther.smol.pub/                          Degrowther 
@https://degrowther.smol.pub/20220801_climate_doomer   Degrowther > Why I'm not a doomer (anymore)
@https://m15o.ichi.city                                m15o 
@https://m15o.ichi.city/site/bookmarklet.html          m15o > bookmarklets
@https://theanarchistlibrary.org                       The Anarchist Library
@https://j3s.sh                                        j3s.sh 
@https://j3s.sh/thought/my-website-is-one-binary.html  j3s.sh > my website is one binary
@https://pfy.ch/                                       pfy.ch 
@https://pfy.ch/photography/photography.html           pfy.ch > Photography
@https://sixey.es/links/                               sixey.es

_Webrings
Webrings rule, browse more webrings!

@https://webring.xxiivv.com/#random   merveilles 
@https://hotlinewebring.club/         Hotline   

---

<h2>Food & Drinks</h2 

@https://grimgrains.com/site/home.html                GrimGrains
@https://i.imgur.com/1dMTDSS.jpeg                     Coffee Grinder Settings
> Start at Encore 10 for espresso, 25 for cafetiere
@https://www.theppk.com                               The Post Punk Kitchen 
@https://www.theppk.com/MLBK_Community_CookZine.pdf   Modern Love Cookzine
@https://cookieandkate.com                            Cookie + Kate

---

-Technology
@https://kaptein.me/blog/sideloading-and-deploying-apps-to-kai-os/  Sideloading Kai OS apps
> Pale Moon 28.6.1 WebIDE works, some newer versions don't.
@https://small-tech.org                                             Small Tech Foundation 
@https://ar.al                                                      Aral Balkan 
@https://casiofanmag.com/manuals/qw3179.pdf                         Casio G-Shock GW-6900 user manual in English
@https://casiofanmag.com/manuals/qw593.pdf                          Casio F-91W user manual in English
@https://compudanzas.itch.io/introduction-to-uxn-programming        Intro to uxn programming, compudanzas


_Photography

@https://www.digitaltruth.com/devchart.php                        Massive Dev Chart, a big list of development times
@https://www.cameramanuals.org/nikon_pdf/nikon_nikkormat_ft.pdf   Nikon Nikkormat FT manual