- 2023-08-23

My laptop is finally on her last legs and has started making the BAD suspicious noises, so there may be a brief break in my posting these while I get a more stable computer setup.

: A pretty bad mental health day today, for a number of reasons --- not least of which I've slept poorly. So one of the my good things today is the lovely nap I took after work that lifted my mood substantiall 🛌
: I finished We Had To Remove This Post, which was really very good if horrifying and tragic. I've started Count Zero next: a different kind of cybernetic horror, maybe 📖
: My partner has been as amazing and loving as they usually are in helping me when I have been having a tough time recently. So, them! 💜 

_ Links

@ https://tilde.town/~dozens/sofa/ SOFA: Start Often, Fuck Achievements

> Want to be somebody who knows how to cook, or code in Lisp? Or somebody who knows how to rollerblade, or only eats plants, or worships the moon? Just start doing those things and then, poof! Now you are that person.

@ /books/fiction/we-had-to-remove-this-post.html We Had To Remove This Post

***

- 2023-08-22

: Made plans to go to the cinema with a friend this weekend 📽️
: I did a legitimate "no walking" run today and am feeling strong 🏃‍♀️
: Went to a friend's for dinner, which was lovely. We hung out and chatted and watched some Old Enough!, the Japanese show where kids do errands for their parents 🍝

_ Links

@ https://blog.protodrew.website/moving_from_gnome_to_sway Protodrew on Sway config, something to try maybe
@ https://reticulum.space/drum-circle.html Drum Circle Computing -- a fantastic idea!

***

- 2023-08-21

: Ate lunch outside today and enjoyed the sun 🌞
: Played some more SSX Tricky, that game is so good 🏂
: Had a really cute date --- we hung out in the park for a while, met some dogs, then went to see Barbie 💖

***

- 2023-08-20

: I went and got breakfast with my partner from a nearby cafe, played some table tennis and went for a walk by the water for a while 🌳
: Partner and I refreshed our undercuts ✂️
: My partner and I went to see boygenius play at Gunnersbury Park. It was basically a cool queer festival: good vibes, great music, nice food! A significant percentage of the polycule was there but signal was pretty bad. We managed to find my girlfriend though! 💜

_ Links

@ https://pixtagram.social/p/hannah/599001679552255654 Some of my photos from boygenius

I took a Kodak Ektar half-frame camera so, expect some more black and white photo nonsense once the roll is finished.

***

- 2023-08-19

I was ill again today and stayed in, which was a bit trying but for the best. Hopefully I'll be well enough for a gig tomorrow.

: I did some more work on the D&D campaign, including watching some videos on Hitman's level design. It's a shame they're all good-aligned, I kind of want to do assassination ideas now 😅
: I got PCSX2 working --- completely legally, of course --- and spent the evening playing THUG and SSX Tricky 🎮
: My partner and I got takeaway ramen for dinner 🍜

_Links

@ https://www.youtube.com/watch?v=sQ0LlNfr8ZI noclip documentary on Hitman's level design

***

- 2023-08-18

I was pretty unwell today unfortunately, which derailed my plans a little. I had to cancel seeing my girlfriend --- that felt pretty shitty.

: Went to see a friend in the morning, and while I ended up having to leave early because I was feeling unwell we did have some pastries and coffee together ☕
: I started learning about COBOL and wrote a 2th-inspired calendar CLI in it 💻
: My partner and I got pizza and watched Game Changer 📺

_ Links

@ https://monadical.com/posts/cobol.html Monadical's article on learning COBOL
@ https://redirect.invidious.io/watch?v=TBs7HXI76yU A very good (if slow) COBOL introductory video
@ https://github.com/hannah-scott/colendar The calendar CLI I wrote

***

- 2023-08-17

: I ordered some more film and it has now arrived! So I went for a lovely photo walk with a cheap half-frame camera 📷
: My friend and I had our first book club session --- we're reading Calling Bullshit. I started making notes and ended up writing about 1,500 words of character assassination on these authors so, good choice 📖
: Two friends came round for dinner and hung out. They're not in the city for long so I'm trying to make the most of their proximity while they're here 🙂

_ Links

@ https://beepb00p.xyz/pkm-setup.html An incredibly personal wiki.

***

- 2023-08-16

: Had a super productive day at work today, including getting VSCode actually working on my laptop and skating to the shops to pick up coffee ☕
: Started reading the latest issue of Branch from Climate Action Tech. I've been doing lots of good reading recently 📖
: I went on a wonderful 2nd date with someone. We went to a metal bar, got food, chilled in the park: blissful 🌳

_Links

@ https://branch.climateaction.tech/ Branch Magazine
@ pixtagram.social/@hannah My Pixelfed account

I'm going to be posting photos to there --- Pixtagram seems like a chill little community.

***

- 2023-08-15

: My partner was home ill today, which was obviously not pleasant but it did mean that I got to spend more time with them in the house 🙂
: I went for a run, which was great --- and started putting together a more robust set of training notes for the marathon 🏃‍♀
: I had my ADHD assessment today, and ended up with a diagnosis. I'm honestly still not sure how I feel about it --- I guess I'll know more when I've spoken to specialists and prescribing doctors --- but it's never a bad thing to have more information about my own brain 🧠

_ Links

@ https://secure77.de/perlite/ Perlite, a publishing platform for Obsidian

Perlite doesn't look great in surf. I'm also not sure what the advantage of publishing my notes is, beyond what I already write up. I understand the advantages of personal wikis --- I don't see the advantage to "writing for an audience".



***

- 2023-08-14

This week is my partner's four-day working week, so they were at home. Working from home is so much nicer knowing they're around.

: Made plans to go see Barbie tomorrow with my partner and girlfriend 💖
: I did a lot of preparation for my D&D campaign (which ended up being postponed for a few days) 🎲
: My partner and I had burgers and watched old Monster Factory episodes. I played some No Man's Sky. Just chilled out, living a weed-free stoner lifestyle 📺

I'm finding Obsidian to be excellent for the kind of work that D&D campaign preparation involves, particularly the canvas view. It's also a lot more performant than Standard Notes or logseq were on my phone, which.

In principle I really like logseq, in practice the mobile app wasn't super usable. It's a shame. I much prefer how it organises to-dos and handles daily journalling.

***

- 2023-08-13

: Church was super chill today. A surprisingly large number of people: we had an interesting preach and took communion together ⛪
: My friend met me after church and we went to the park together to eat galettes and catch up. We chatted about what we were reading, how life is going, work 🌳
: I cooked for myself, my partner and girlfriend, and my friend and her boyfriend. It was lovely to just hang out with everyone, cook for them, chat and laugh. A beautiful evening 🥘

***

- 2023-08-12
: I had a first date today with someone from the apps and it went so well. She was so cool! We went to a cute cafe and hung out in the park petting dogs -- chill times ☺️
: Had delicious lunch at a nearby cafe and chilled in the sun 🌞
: My partner and I watched They Cloned Tyrone: hilarious and super socially conscious, with fantastic performances. It also looked incredible. Highly recommend it 📽️

_ Links

@ https://bookshelf.theanarchistlibrary.org/library/librarian-picks The Anarchist Library's librarians pick their fave books
@ https://theanarchistlibrary.org/library/james-c-scott-seeing-like-a-state Seeing like a State, James C. Scott

I finished the introduction to Seeing like a State today. It's exploring an idea that I've heard a lot about before --- legibility --- in much more detail than I've ever thought about it.

***

- 2023-08-11

:  I went skating after work and landed some BS shuvits, which I must have last done like 6 years ago or something 🛹
:  My partner had a date, so I watched stuff they wouldn't be in to. Ended up going through the first episode of The Rehearsal, and the third instalment in the God's Not Dead series, which honestly was kinda watchable compared to the first two 📽
:  I ate dinner in the park and chilled in the sunset 🥖

_Links

@ https://theanarchistlibrary.org/library/nekeisha-alexis-baker-embracing-god-and-rejecting-masters Embracing God and Rejecting Masters, Nekeisha Alexis-Baker

Obviously I think Christianity and anarchism have a lot to share with each other, it's nice to read that other people do too!

***

- 2023-08-10

:  I went skating at lunch. It was baking hot but super fun 🛹
:  Partner and I had friends over, we played Catan and ate arepas 🎲
:  I implemented some seasonal stylesheets on my website 🖥

***

- 2023-08-09

: Had a day in the office with my team today, which I had organised. It went really well, we got a lot done and it was nice seeing everyone in person 💻
: Went for a drink with work people afterwards, which was fun 🍻
: Watched some TV and had delicious Mediterranean vegetable pasta for dinner pasta 🍝

_ Links

@ https://docs.raku.org Documentation for Raku/Perl 6, which looks weird as all fuck!

***

- 2023-08-08

:  I completed the prework for my ADHD assessment next week, looking forward to having that conversation 🧠
:  I had a panic attack -- bad -- but this motivated my to build a JS-free tool to do breathing exercises -- good! 🌬
:  My girlfriend and I saw Oppenheimer -- it was pretty good! She described it as "physicist Avengers", which is entirely fair 📽

_ Links

@ /breathe/ My JS-free breathing exercise tool

***

- 2023-08-07

: In polyamorous news, I'm back on the apps and possibly have a date! Early dating is so fun and exciting and new, turns out people are pretty cool and interesting -- who knew? 🙂
: I got my injection sorted. The practice nurse at my doctor's is such a friendly person 👩‍⚕️
: Made plans to go see Oppenheimer with my girlfriend, and to see my friend this weekend. Busy social times! 📆

_ Links

@ https://theanarchistlibrary.org/library/susan-song-polyamory-and-queer-anarchism-infinite-possibilities-for-resistance I reread Polyamory and Queer Anarchism 
@ https://theanarchistlibrary.org/library/peter-gelderloos-the-poisons-are-already-in-here-with-us and started this transcript of a talk given by Peter Gelderloos

I'm also acquired a copy of Calling Bullshit for my book club. It's interesting: I think there's influence from David Graeber's fantastic book, but a lot more politically toothless based on the first couple of chapters.

***

- 2023-08-06

: Church was super relaxed and chilled out today, which honestly I needed -- I'm so tired... sang some songs and caught up with folks ⛪
: I went to the park and got lunch from a great food stall, chatted to the person who works there for a bit then sat in the sun and ate 🌞
: I went to see my girlfriend! We had a lovely dinner and started the new season of The Bear 🐻

! /img/three-good-things/jersey-tiger.jpg A Jersey Tiger moth, quite large with bold black and white stripes, chilling on a doorframe.

_ Links

@ https://surma.dev/things/ditherpunk/ A fun interesting overview on dithering techniques


***

-  2023-08-05

: Partner and I did a kind of big house tidy, it looks so lovely 🏠
: We went to a nearby cafe, I had a really good bagel and a pistachio pain au chocolat 🥐
: We went to our social sibling's birthday party, which was a costume party! I was Lara Croft and so were they 🔫

***

- 2023-08-04

: Made plans with my friend to start a book club, and suggested a couple of things for our first book 📖
: Knees and ankles are both absolutely wrecked so no skating or running today, but I did bike to a nearby green space to eat my lunch and listen to Trashfuture 🌳
: My partner and I got pizza for dinner from a place that does cheesy garlic bread with olives 🍕

! /img/three-good-things/TOUGHSQUIRREL.jpg A close-up photo of a squirrel taken through a window. The squirrel has its paw up on the glass and is leering in.

This friend was trying to get in while I was working, which --- I admire the energy, yeah. Took some self-control not to make a friend with a squirrel. I kinda regret it, really. Squirrel-friend would be cool.

_ Links

@ https://betula.mycorrhiza.wiki/v1.0.0.html betula, a cool bookmarking tool - I've moved my bookmarks over to it
@ https://www.inkandswitch.com/local-first/static/local-first.pdf A paper by Ink & Switch on local-first software

***

- 2023-08-03

: My partner and I got almond croissants from a coffee shop nearby for breakfast 🥐
: I skated a lot today: chatted to someone I knew at the park, hit some rock to fakies for the first time in a while, and rolled into a quarterpipe for the first time ever 🛹
: My partner came to meet me at the skatepark and brought some ciders, so we hung out in the park enjoying the evening sun and chilling 🍻

_ Links

@ https://consc.net/papers/extended.html The Extended Mind by Clark and Chalmers, I've been reading this today

***

- 2023-08-02

:  I cooked a pretty great aubergine and chickpea curry with chapatti --- a couple days of cooking in a row is doing nice things for my mental health, so I might try to keep that up for a while 🍽
:  I made plans for this weekend with my girlfriend 💜
:  I went for a run after work. Running around the park through mud and with a slight chill in the air has me excited for autumn 🏃‍♀

_ Links

@ https://ploum.net/2023-08-01-splitting-the-web.html Ploum's piece on "splitting the web" and getting away from ad-tech
@ https://obsidian.md I'm trying out Obsidian as a note-taking platform, so far I'm enjoying it --- not sure how I feel about choosing to use closed-source software, but I guess I can always move away to a different Markdown-based solution

***

- 2023-08-01

:	I went skating at lunch, chatted to a couple people at the park and got talked into trying out some roll-on grinds. Those are insanely fucking fun! It's meant to rain for the next few days, so it was good to get some skating in before then 🛹
: I baked some tofu until it was super crispy and served it with a roasted pepper vegan mac & cheese. Turned out really nicely 🫑
: I started trying out anki and spaced repetition as a general note-taking system, a way to reinforce patterns and practices. I'm interested to see how it works 🙂

!/img/three-good-things/pepper.jpg A red sweet pointed pepper roasting on a gas hob.

_ Links
@ https://www.theguardian.com/artanddesign/2023/jul/31/damn-i-wanna-be-like-her-londons-women-skaters-photo-essay Guardian photo essay about girls and women who skate
@ https://invidious.fdn.fr/watch?v=aCiYmCVikjo&local=true The Dead Kennedys -- Let's Lynch The Landlord
@ https://notes.andymatuschak.org/z53zJy6y76MGuJuWW4Qvab9 Andy Matuschak's evergreen notes on spaced repetition

***

- 2023-07-31

: I got my markup language lark to a releasable state, so --- it's out! A couple changes to how blocks work, and a much cleaner implenentation 💻
: My parents brought me a guitar so my partner and I have been singing --- mostly boygenius, but I sang some Pat the Bunny songs too 🎸
: My partner made this gorgeous green bean and pasta dish with cooked lemons 🍝

_ Links

@ https://github.com/hannah-scott/lark lark on github
@ https://github.com/todotxt/todo.txt Todo.txt reference guide
@ https://invidious.fdn.fr/watch?v=FSa9cNQYR6k Wingnut Dishwashers Union -- Burn the Earth! Leave it Behind!

***

- 2023-07-30

Today marks a year of Three Good Things, so --- happy anniversary 🙂

: 	I got up and made nice coffee, and had some of the peanut butter snacks my parents brought ☕
: 	My partner and I went to London zoo for the day --- we saw loads of cool animals, including some cool glasswing butterflies. I'm not the biggest fan of zoos but today was really lovely 🦋
: 	We watched What's Love Got To Do With It? which was pretty good, and some very chill youtube videos by tanks for nothin setting up fishtanks 🐌

_ Pictures

!/img/2023-07-30-zoo-trip/lizard.jpg A green lizard climbing out of the water
!/img/2023-07-30-zoo-trip/butterfly.jpg A glasswing butterfly on a leaf, next to a bright orange flower
!/img/2023-07-30-zoo-trip/pigs.jpg Three orange pigs rooting around in the dirt
@/img/2023-07-30-zoo-trip/spider.jpg (CW: Picture of a spider) A male orb spider

_ Links

@gemini://zaibatsu.circumlunar.space/~solderpunk/gemlog/do-you-even-compute-bro.gmi (Gemini) Solderpunk --- Do you even compute bro?
@https://invidious.fdn.fr/channel/UCJXxuESjGIaaqb1-IRWFihw tanks for nothin's youtube channel