- 2023-08-04

: Made plans with my friend to start a book club, and suggested a couple of things for our first book 📖
: Knees and ankles are both absolutely wrecked so no skating or running today, but I did bike to a nearby green space to eat my lunch and listen to Trashfuture 🌳
: My partner and I got pizza for dinner from a place that does cheesy garlic bread with olives 🍕

! /img/three-good-things/TOUGHSQUIRREL.jpg A close-up photo of a squirrel taken through a window. The squirrel has its paw up on the glass and is leering in.

This friend was trying to get in while I was working, which --- I admire the energy, yeah. Took some self-control not to make a friend with a squirrel. I kinda regret it, really. Squirrel-friend would be cool.

_ Links

@ https://betula.mycorrhiza.wiki/v1.0.0.html betula, a cool bookmarking tool - I've moved my bookmarks over to it
@ https://www.inkandswitch.com/local-first/static/local-first.pdf A paper by Ink & Switch on local-first software

***

- 2023-08-03

: My partner and I got almond croissants from a coffee shop nearby for breakfast 🥐
: I skated a lot today: chatted to someone I knew at the park, hit some rock to fakies for the first time in a while, and rolled into a quarterpipe for the first time ever 🛹
: My partner came to meet me at the skatepark and brought some ciders, so we hung out in the park enjoying the evening sun and chilling 🍻

_ Links

@ https://consc.net/papers/extended.html The Extended Mind by Clark and Chalmers, I've been reading this today

***

- 2023-08-02

:  I cooked a pretty great aubergine and chickpea curry with chapatti --- a couple days of cooking in a row is doing nice things for my mental health, so I might try to keep that up for a while 🍽
:  I made plans for this weekend with my girlfriend 💜
:  I went for a run after work. Running around the park through mud and with a slight chill in the air has me excited for autumn 🏃‍♀

_ Links

@ https://ploum.net/2023-08-01-splitting-the-web.html Ploum's piece on "splitting the web" and getting away from ad-tech
@ https://obsidian.md I'm trying out Obsidian as a note-taking platform, so far I'm enjoying it --- not sure how I feel about choosing to use closed-source software, but I guess I can always move away to a different Markdown-based solution

***

- 2023-08-01

:	I went skating at lunch, chatted to a couple people at the park and got talked into trying out some roll-on grinds. Those are insanely fucking fun! It's meant to rain for the next few days, so it was good to get some skating in before then 🛹
: I baked some tofu until it was super crispy and served it with a roasted pepper vegan mac & cheese. Turned out really nicely 🫑
: I started trying out anki and spaced repetition as a general note-taking system, a way to reinforce patterns and practices. I'm interested to see how it works 🙂

!/img/three-good-things/pepper.jpg A red sweet pointed pepper roasting on a gas hob.

_ Links
@ https://www.theguardian.com/artanddesign/2023/jul/31/damn-i-wanna-be-like-her-londons-women-skaters-photo-essay Guardian photo essay about girls and women who skate
@ https://invidious.fdn.fr/watch?v=aCiYmCVikjo&local=true The Dead Kennedys -- Let's Lynch The Landlord
@ https://notes.andymatuschak.org/z53zJy6y76MGuJuWW4Qvab9 Andy Matuschak's evergreen notes on spaced repetition

***

- 2023-07-31

: I got my markup language lark to a releasable state, so --- it's out! A couple changes to how blocks work, and a much cleaner implenentation 💻
: My parents brought me a guitar so my partner and I have been singing --- mostly boygenius, but I sang some Pat the Bunny songs too 🎸
: My partner made this gorgeous green bean and pasta dish with cooked lemons 🍝

_ Links

@ https://github.com/hannah-scott/lark lark on github
@ https://github.com/todotxt/todo.txt Todo.txt reference guide
@ https://invidious.fdn.fr/watch?v=FSa9cNQYR6k Wingnut Dishwashers Union -- Burn the Earth! Leave it Behind!

***

- 2023-07-30

Today marks a year of Three Good Things, so --- happy anniversary 🙂

: 	I got up and made nice coffee, and had some of the peanut butter snacks my parents brought ☕
: 	My partner and I went to London zoo for the day --- we saw loads of cool animals, including some cool glasswing butterflies. I'm not the biggest fan of zoos but today was really lovely 🦋
: 	We watched What's Love Got To Do With It? which was pretty good, and some very chill youtube videos by tanks for nothin setting up fishtanks 🐌

_ Pictures

!/img/2023-07-30-zoo-trip/lizard.jpg A green lizard climbing out of the water
!/img/2023-07-30-zoo-trip/butterfly.jpg A glasswing butterfly on a leaf, next to a bright orange flower
!/img/2023-07-30-zoo-trip/pigs.jpg Three orange pigs rooting around in the dirt
@/img/2023-07-30-zoo-trip/spider.jpg (CW: Picture of a spider) A male orb spider

_ Links

@gemini://zaibatsu.circumlunar.space/~solderpunk/gemlog/do-you-even-compute-bro.gmi (Gemini) Solderpunk --- Do you even compute bro?
@https://invidious.fdn.fr/channel/UCJXxuESjGIaaqb1-IRWFihw tanks for nothin's youtube channel