- 2023-07-28

:  Made some really good progress on the markup language (we're calling it lark), to the point that it can read three good things entries 💯
:  I saw some really cool 70's Glaswegian skate pictures on Mastodon 🛹
:  I'm meeting up with my parents tonight for dinner and drinks 💑

_ Links

@https://www.northskatemag.com/blogs/north-latest/kelvingrove North Skate Magazine's article on Kelvingrove skatepark

***

- 2023-07-27

:  I skated to the shops and back, which I always love doing 🛹
:  My partner and I made an aubergine and tofu dish on rice which came out super nicely 🍚
:  I started work on a light markup language that I'm planning to implement three good things and other parts of my website in. Will link when it's usable ✏️

***

- 2023-07-26

:  Album today was Be by Common, which I loved! 🎧
:  Partner and I watched (all of) We Are Lady Parts, great show 📺
:  I went for a run and felt really strong --- training is going well 🏃‍♀️

***